# Generated by Django 4.1.1 on 2022-11-17 14:12

import NR10.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("utils", "0009_alter_anotacao_author"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eletricista",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "certificados",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("recebimento", models.DateField(blank=True, null=True)),
                ("anomalia", models.CharField(blank=True, max_length=40, null=True)),
                ("material_disponivel", models.DateField(blank=True, null=True)),
                (
                    "componentes_utilizados",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                ("reparo", models.DateField(blank=True, null=True)),
                ("prateleria", models.CharField(blank=True, max_length=1)),
                (
                    "imagem",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=None,
                        verbose_name="Foto de Perfil",
                    ),
                ),
                (
                    "updated_at",
                    NR10.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="utils.area",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=80)),
                ("tipo", models.CharField(max_length=20)),
                (
                    "descricao",
                    models.CharField(blank=True, default=" ", max_length=1024),
                ),
                (
                    "create_at",
                    NR10.models.AutoDateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Documentos",
                        to="NR10.eletricista",
                    ),
                ),
            ],
        ),
    ]
