# Generated by Django 4.1.1 on 2022-11-17 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NR10",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="NR10Complementar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name="eletricista",
            old_name="anomalia",
            new_name="cargo",
        ),
        migrations.RemoveField(
            model_name="eletricista",
            name="certificados",
        ),
        migrations.RemoveField(
            model_name="eletricista",
            name="componentes_utilizados",
        ),
        migrations.RemoveField(
            model_name="eletricista",
            name="material_disponivel",
        ),
        migrations.RemoveField(
            model_name="eletricista",
            name="prateleria",
        ),
        migrations.RemoveField(
            model_name="eletricista",
            name="recebimento",
        ),
        migrations.RemoveField(
            model_name="eletricista",
            name="reparo",
        ),
        migrations.RemoveField(
            model_name="eletricista",
            name="updated_at",
        ),
        migrations.DeleteModel(
            name="Documento",
        ),
        migrations.AddField(
            model_name="nr10complementar",
            name="dono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="NR10_complementar",
                to="NR10.eletricista",
            ),
        ),
        migrations.AddField(
            model_name="nr10",
            name="dono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="NR10",
                to="NR10.eletricista",
            ),
        ),
    ]
