# Generated by Django 4.1.1 on 2022-11-17 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("utils", "0009_alter_anotacao_author"),
        ("NR10", "0002_nr10_nr10complementar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eletricista",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="utils.area",
                verbose_name="Área",
            ),
        ),
        migrations.AlterField(
            model_name="nr10",
            name="dono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nr10",
                to="NR10.eletricista",
            ),
        ),
        migrations.AlterField(
            model_name="nr10complementar",
            name="dono",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nr10_Complementar",
                to="NR10.eletricista",
            ),
        ),
    ]
