# Generated by Django 4.1.1 on 2022-11-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0003_alter_eletricista_area_alter_nr10_dono_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="nr10complementar",
            name="certificado",
            field=models.FileField(
                default=1, max_length=254, upload_to="NR10/NR10Complementar/"
            ),
            preserve_default=False,
        ),
    ]
