# Generated by Django 4.1.1 on 2022-11-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0004_nr10complementar_certificado"),
    ]

    operations = [
        migrations.AddField(
            model_name="nr10",
            name="certificado",
            field=models.FileField(default=1, max_length=254, upload_to="NR10/NR10/"),
            preserve_default=False,
        ),
    ]
