# Generated by Django 4.1.1 on 2022-11-17 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("NR10", "0005_nr10_certificado"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nr10",
            options={
                "ordering": ["id"],
                "verbose_name": "NR10 Complementar",
                "verbose_name_plural": "NR10 Complementar",
            },
        ),
        migrations.AlterModelOptions(
            name="nr10complementar",
            options={
                "ordering": ["id"],
                "verbose_name": "NR10 Complementar",
                "verbose_name_plural": "NR10's Complementares",
            },
        ),
        migrations.AlterField(
            model_name="eletricista",
            name="imagem",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="NR10/foto/",
                verbose_name="Foto de Perfil",
            ),
        ),
        migrations.CreateModel(
            name="Asu",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateField()),
                (
                    "certificado",
                    models.FileField(max_length=254, upload_to="NR10/ASU/"),
                ),
                (
                    "dono",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Asu",
                        to="NR10.eletricista",
                    ),
                ),
            ],
            options={
                "verbose_name": "ASU",
                "verbose_name_plural": "ASU's",
            },
        ),
    ]
